### ISSUE TITLE
Consolidar crawlers?

### ISSUE THREAD

**Issue by caiocarrara** [marcosfons/brumadinho_crawler#1]
Olá, @marcosfons! Tudo bom?

Estamos com a ideia de consolidar os crawlers relacionados a Brumadinho em um único projeto. Quem sabe até consolidar as buscas de todos os crawlers em somente um dataset. O que acha de adicionar esse seu crawler no projeto? Está sob a organização `SOSBrumadinho`[1]. Se topar, abre um PR lá que aceito rapidamente. É só você colocar esse seu script abaixo do diretório crawlers. Depois eu posso tocar a consolidação.

[1] - https://github.com/sosbrumadinho/brumadinho_crawlers

Abraço!

**Comment by marcosfons** [comment]
Acabei vendo hoje apenas, infelizmente esse crawler não é tão preciso. Por usar o leitor de imagem, as vezes não reconhece todos os nomes. Ainda acha que é válido?

**Comment by caiocarrara** [comment]
Colocando no repositório centralizado lá e cadastrando as issues de melhoria alguém pode te ajudar. Veja ai o que vc prefere.
